name: Auto-merge successful PRs

on:
  pull_request:
    types: [opened, synchronize]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' && 
      (startsWith(github.head_ref, 'renovate/') || github.actor == 'renovate[bot]') &&
      contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Test builds on all platforms
        id: test
        run: |
          echo "Testing builds on all supported platforms..."

          # Define platforms
          PLATFORMS=("x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin")
          PACKAGES=("gcs" "opencode")
          BUILD_SUCCESS=true

          # Test each package on each platform
          for platform in "${PLATFORMS[@]}"; do
            echo "Testing platform: $platform"
            
            for package in "${PACKAGES[@]}"; do
              echo "  Building $package for $platform..."
              
              if ! nix build .#$package --system $platform --no-link; then
                echo "❌ $package build failed on $platform"
                BUILD_SUCCESS=false
              else
                echo "✅ $package build successful on $platform"
              fi
            done
          done

          if [[ "$BUILD_SUCCESS" == "true" ]]; then
            echo "build_success=true" >> $GITHUB_OUTPUT
            echo "🎉 All builds successful on all platforms!"
          else
            echo "build_success=false" >> $GITHUB_OUTPUT
            echo "💥 One or more builds failed"
          fi

      - name: Auto-merge PR
        if: steps.test.outputs.build_success == 'true'
        uses: pascalgn/merge-action@v0.15.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          merge_commit_message: pull-request-title

      - name: Comment on failed build
        if: steps.test.outputs.build_success == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Auto-merge failed**: Build tests did not pass on all platforms.\n\n**Tested platforms:**\n- x86_64-linux\n- aarch64-linux\n- x86_64-darwin\n- aarch64-darwin\n\nPlease check the build logs and fix any issues before merging.'
            })
