name: Test Builds

on:
  pull_request:
    types: [synchronize]
    branches: [master]

permissions:
  contents: read # For checkout

jobs:
  # SECURITY: Validate that this is a legitimate Renovate PR build test
  security-validation:
    name: "Security Validation"
    runs-on: ubuntu-latest
    # NOTE: In pull_request synchronize events, github.actor is the PR author
    # (renovate[bot]), not the commit author. We check commit author and message
    # to detect hash update commits.
    if: |
      github.event.head_commit.author.username == 'github-actions[bot]' ||
      contains(github.event.head_commit.message, 'package hashes')
    outputs:
      is-secure: ${{ steps.validate.outputs.is-secure }}
      package: ${{ steps.extract-package.outputs.package }}
      pr-number: ${{ github.event.pull_request.number }}
      commit-sha: ${{ github.event.pull_request.head.sha }}
      branch-ref: ${{ github.head_ref }}
    steps:
      - name: Debug event context
        run: |
          echo "=== GITHUB EVENT CONTEXT DEBUG ==="
          echo "Actor: ${{ github.actor }}"
          echo "Triggering Actor: ${{ github.triggering_actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Head Commit SHA: ${{ github.event.head_commit.id }}"
          echo "Head Commit Author: ${{ github.event.head_commit.author.username }}"
          echo "Head Commit Message: ${{ github.event.head_commit.message }}"
          echo "PR Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
          echo "Branch: ${{ github.head_ref }}"
          echo "Base Branch: ${{ github.base_ref }}"

      - name: Extract package name from PR title
        id: extract-package
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"

          # Extract package name between "update " and " to "
          PACKAGE=$(echo "$PR_TITLE" | \
            sed -n 's/.*update \([^ ]*\) to.*/\1/p')

          if [[ -z "$PACKAGE" ]]; then
            echo "❌ ERROR: Failed to extract package name from PR title"
            exit 1
          fi

          echo "Detected package: $PACKAGE"
          echo "package=$PACKAGE" >> $GITHUB_OUTPUT

      - name: Validate build test security
        id: validate
        uses: actions/github-script@v7
        with:
          script: |
            console.log("=== BUILD MATRIX SECURITY VALIDATION ===");

            const prNumber = ${{ github.event.pull_request.number }};
            const commitSha = '${{ github.event.pull_request.head.sha }}';
            const package = '${{ steps.extract-package.outputs.package }}';
            const branchRef = '${{ github.head_ref }}';
            const prAuthor = '${{ github.event.pull_request.user.login }}';
            const prTitle = '${{ github.event.pull_request.title }}';
            const headCommitAuthor = '${{ github.event.head_commit.author.username }}';
            const headCommitMessage = '${{ github.event.head_commit.message }}';

            console.log(`PR Number: ${prNumber}`);
            console.log(`Commit SHA: ${commitSha}`);
            console.log(`Package: ${package}`);
            console.log(`Branch Ref: ${branchRef}`);
            console.log(`Triggered by: ${context.actor}`);
            console.log(`PR Author: ${prAuthor}`);
            console.log(`PR Title: ${prTitle}`);
            console.log(`Head Commit Author: ${headCommitAuthor}`);
            console.log(`Head Commit Message: ${headCommitMessage}`);

            // SECURITY CHECK: Commit must be from github-actions[bot] OR
            // contain hash update message
            const isHashUpdateCommit = headCommitAuthor === 'github-actions[bot]' ||
                                     headCommitMessage.includes('package hashes');

            if (!isHashUpdateCommit) {
              console.log(`❌ SECURITY: Commit author is '${headCommitAuthor}' ` +
                         `and message does not contain 'package hashes'`);
              core.setOutput('is-secure', 'false');
              return;
            }

            // SECURITY CHECK: PR must be from renovate[bot]
            if (prAuthor !== 'renovate[bot]') {
              console.log(`❌ SECURITY: PR author is '${prAuthor}', ` +
                         `not 'renovate[bot]'`);
              core.setOutput('is-secure', 'false');
              return;
            }

            // SECURITY CHECK: Branch must have renovate prefix
            if (!branchRef.startsWith('update/')) {
              console.log(`❌ SECURITY: Branch '${branchRef}' ` +
                         `does not have renovate prefix`);
              core.setOutput('is-secure', 'false');
              return;
            }

            // SECURITY CHECK: PR title must match pattern
            if (!prTitle.match(/^chore: update .+ to .+$/)) {
              console.log(`❌ SECURITY: PR title '${prTitle}' ` +
                         `does not match expected pattern`);
              core.setOutput('is-secure', 'false');
              return;
            }

            console.log("✅ SECURITY: Build matrix validation passed");
            core.setOutput('is-secure', 'true');

  build-matrix:
    needs: security-validation
    if: needs.security-validation.outputs.is-secure == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x86_64-linux
            runner: ubuntu-latest
          - platform: aarch64-linux
            runner: ubuntu-latest
          - platform: x86_64-darwin
            runner: macos-13
          - platform: aarch64-darwin
            runner: macos-14
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.security-validation.outputs.commit-sha }}

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build package on ${{ matrix.platform }}
        run: |
          PACKAGE="${{ needs.security-validation.outputs.package }}"
          PLATFORM="${{ matrix.platform }}"

          echo "=== Building $PACKAGE on $PLATFORM ==="
          echo "Package: $PACKAGE"
          echo "Platform: $PLATFORM"
          echo "Commit SHA: ${{ needs.security-validation.outputs.commit-sha }}"

          # Use the build-package script for consistent builds
          if ./bin/build-package --platform "$PLATFORM" --package "$PACKAGE"; then
            echo "✅ Build successful: $PACKAGE on $PLATFORM"
          else
            echo "❌ Build failed: $PACKAGE on $PLATFORM"
            exit 1
          fi
