name: Test Builds

on:
  pull_request:
    types: [synchronize]
    branches: [master]

permissions:
  contents: read # For checkout
  pull-requests: write # For PR comments
  issues: write # For issue comments

jobs:
  # SECURITY: Validate that this is a legitimate Renovate PR build test
  security-validation:
    name: "Security Validation"
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]'
    outputs:
      is-secure: ${{ steps.validate.outputs.is-secure }}
      package: ${{ steps.extract-package.outputs.package }}
      pr-number: ${{ github.event.pull_request.number }}
      commit-sha: ${{ github.event.pull_request.head.sha }}
      branch-ref: ${{ github.head_ref }}
    steps:
      - name: Extract package name from PR title
        id: extract-package
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"

          # Extract package name between "update " and " to "
          PACKAGE=$(echo "$PR_TITLE" | \
            sed -n 's/.*update \([^ ]*\) to.*/\1/p')

          if [[ -z "$PACKAGE" ]]; then
            echo "❌ ERROR: Failed to extract package name from PR title"
            exit 1
          fi

          echo "Detected package: $PACKAGE"
          echo "package=$PACKAGE" >> $GITHUB_OUTPUT

      - name: Validate build test security
        id: validate
        uses: actions/github-script@v7
        with:
          script: |
            console.log("=== BUILD MATRIX SECURITY VALIDATION ===");

            const prNumber = ${{ github.event.pull_request.number }};
            const commitSha = '${{ github.event.pull_request.head.sha }}';
            const package = '${{ steps.extract-package.outputs.package }}';
            const branchRef = '${{ github.head_ref }}';
            const prAuthor = '${{ github.event.pull_request.user.login }}';
            const prTitle = '${{ github.event.pull_request.title }}';

            console.log(`PR Number: ${prNumber}`);
            console.log(`Commit SHA: ${commitSha}`);
            console.log(`Package: ${package}`);
            console.log(`Branch Ref: ${branchRef}`);
            console.log(`Triggered by: ${context.actor}`);
            console.log(`PR Author: ${prAuthor}`);
            console.log(`PR Title: ${prTitle}`);

            // SECURITY CHECK: Actor must be github-actions[bot]
            if (context.actor !== 'github-actions[bot]') {
              console.log(`❌ SECURITY: Actor is '${context.actor}', ` +
                         `not 'github-actions[bot]'`);
              core.setOutput('is-secure', 'false');
              return;
            }

            // SECURITY CHECK: PR must be from renovate[bot]
            if (prAuthor !== 'renovate[bot]') {
              console.log(`❌ SECURITY: PR author is '${prAuthor}', ` +
                         `not 'renovate[bot]'`);
              core.setOutput('is-secure', 'false');
              return;
            }

            // SECURITY CHECK: Branch must have renovate prefix
            if (!branchRef.startsWith('update/')) {
              console.log(`❌ SECURITY: Branch '${branchRef}' ` +
                         `does not have renovate prefix`);
              core.setOutput('is-secure', 'false');
              return;
            }

            // SECURITY CHECK: PR title must match pattern
            if (!prTitle.match(/^chore: update .+ to .+$/)) {
              console.log(`❌ SECURITY: PR title '${prTitle}' ` +
                         `does not match expected pattern`);
              core.setOutput('is-secure', 'false');
              return;
            }

            console.log("✅ SECURITY: Build matrix validation passed");
            core.setOutput('is-secure', 'true');

  build-matrix:
    name: "Build Matrix - ${{ matrix.platform }}"
    needs: security-validation
    if: needs.security-validation.outputs.is-secure == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x86_64-linux
            runner: ubuntu-latest
          - platform: aarch64-linux
            runner: ubuntu-latest
          - platform: x86_64-darwin
            runner: macos-13
          - platform: aarch64-darwin
            runner: macos-14
    runs-on: ${{ matrix.runner }}
    outputs:
      matrix-success: ${{ steps.matrix-result.outputs.success }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.security-validation.outputs.commit-sha }}

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build package on ${{ matrix.platform }}
        id: build
        run: |
          PACKAGE="${{ needs.security-validation.outputs.package }}"
          PLATFORM="${{ matrix.platform }}"

          echo "=== Building $PACKAGE on $PLATFORM ==="
          echo "Package: $PACKAGE"
          echo "Platform: $PLATFORM"
          echo "Commit SHA: ${{ needs.security-validation.outputs.commit-sha }}"

          # Use the build-package script for consistent builds
          if ./bin/build-package --platform "$PLATFORM" --package "$PACKAGE"; then
            echo "✅ Build successful: $PACKAGE on $PLATFORM"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Build failed: $PACKAGE on $PLATFORM"
            echo "success=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Set matrix job result
        id: matrix-result
        if: always()
        run: |
          if [[ "${{ steps.build.outcome }}" == "success" ]]; then
            echo "success=true" >> $GITHUB_OUTPUT
            echo "✅ Matrix job succeeded for ${{ matrix.platform }}"
          else
            echo "success=false" >> $GITHUB_OUTPUT
            echo "❌ Matrix job failed for ${{ matrix.platform }}"
          fi

  aggregate-results:
    name: "Aggregate Results"
    runs-on: ubuntu-latest
    needs: [security-validation, build-matrix]
    if: always()
    outputs:
      all-builds-success: ${{ steps.aggregate.outputs.success }}
      failed-platforms: ${{ steps.aggregate.outputs.failed-platforms }}
    steps:
      - name: Aggregate build results
        id: aggregate
        run: |
          echo "=== Aggregating Build Matrix Results ==="

          # Check the overall result of the matrix job
          MATRIX_RESULT="${{ needs.build-matrix.result }}"
          echo "Matrix job result: $MATRIX_RESULT"

          if [[ "$MATRIX_RESULT" == "success" ]]; then
            echo "✅ All platform builds succeeded"
            echo "success=true" >> $GITHUB_OUTPUT
            echo "failed-platforms=" >> $GITHUB_OUTPUT
          else
            echo "❌ One or more platform builds failed"
            echo "success=false" >> $GITHUB_OUTPUT
            # For now, use placeholder for failed platforms
            # Future enhancement: parse individual matrix job results
            echo "failed-platforms=PLACEHOLDER" >> $GITHUB_OUTPUT
          fi

  # TODO: Re-enable when auto-merge.yml workflow is implemented
  # trigger-auto-merge:
  #   name: "Trigger Auto-merge"
  #   runs-on: ubuntu-latest
  #   needs: [security-validation, build-matrix, aggregate-results]
  #   if: always() && needs.aggregate-results.outputs.all-builds-success == 'true'
  #   steps:
  #     - name: Trigger auto-merge workflow
  #       uses: actions/github-script@v7
  #       with:
  #         script: |
  #           const prNumber = '${{ needs.security-validation.outputs.pr-number }}';
  #           const branchRef = '${{ needs.security-validation.outputs.branch-ref }}';
  #           const package = '${{ needs.security-validation.outputs.package }}';
  #
  #           console.log(`✅ All builds successful - triggering auto-merge`);
  #           console.log(`PR Number: ${prNumber}`);
  #           console.log(`Branch Ref: ${branchRef}`);
  #           console.log(`Package: ${package}`);
  #
  #           // Trigger auto-merge workflow
  #           await github.rest.actions.createWorkflowDispatch({
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             workflow_id: 'auto-merge.yml',
  #             ref: 'master',
  #             inputs: {
  #               pr_number: prNumber,
  #               pr_ref: branchRef,
  #               build_success: 'true'
  #             }
  #           });
  #
  #           console.log(`🚀 Auto-merge workflow triggered for PR ${prNumber}`);

  report-failure:
    name: "Report Failure"
    runs-on: ubuntu-latest
    needs: [security-validation, build-matrix, aggregate-results]
    if: always() && needs.aggregate-results.outputs.all-builds-success == 'false'
    steps:
      - name: Comment on failed build
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = '${{ needs.security-validation.outputs.pr-number }}';
            const package = '${{ needs.security-validation.outputs.package }}';
            const failedPlatforms = '${{ needs.aggregate-results.outputs.failed-platforms }}';

            const comment = `❌ **Build Matrix Failed**

            Package: ${package}
            Failed Platforms: ${failedPlatforms}
            Error Details: PLACEHOLDER

            Some platform builds failed. Please check the build logs for details.

            **Tested platforms:**
            - x86_64-linux
            - aarch64-linux  
            - x86_64-darwin
            - aarch64-darwin

            🔒 **Security validated**: This is a legitimate Renovate PR`;

            await github.rest.issues.createComment({
              issue_number: parseInt(prNumber),
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

            console.log(`💬 Failure comment posted to PR ${prNumber}`);
