name: Update Nix Hashes

on:
  pull_request:
    paths:
      - "packages/*.nix"
  workflow_dispatch:

jobs:
  update-hashes:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Update GCS hashes
        id: update-gcs
        run: |
          echo "Running GCS update script..."
          if ./bin/update-gcs.sh; then
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "GCS update failed or no update needed"
          fi

      - name: Update OpenCode hashes
        id: update-opencode
        run: |
          echo "Running OpenCode update script..."
          if ./bin/update-opencode.sh; then
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "OpenCode update failed or no update needed"
          fi

      - name: Test all builds
        run: |
          echo "Testing all package builds..."
          echo "Building GCS..."
          nix build .#gcs
          echo "Building OpenCode..."
          nix build .#opencode
          echo "All builds successful!"

      - name: Commit hash updates
        if: steps.update-gcs.outputs.updated == 'true' || steps.update-opencode.outputs.updated == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add packages/*.nix

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update nix package hashes - auto-updated by GitHub Actions"
            git push
          fi
